models/Article.php
<?php

namespace app\models;


use Yii;
use app\models\Coment;

/**
 * This is the model class for table "Article".
 *
 * @property integer $ID
 * @property string $Title
 * @property string $Content
 * @property string $CreatedAt
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Title', 'Content'], 'required'],
            [['Content'], 'string'],
            [['CreatedAt'], 'safe'],
            [['Title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => Yii::t('app', 'ID'),
            'Title' => Yii::t('app', 'Title'),
            'Content' => Yii::t('app', 'Content'),
            'CreatedAt' => Yii::t('app', 'Created At'),
        ];
    }
    public function beforeSave($insert)
    {
         parent::beforeSave($insert); // TODO: Change the autogenerated stub
        $this->CreatedAt = date('c',strtotime($this->CreatedAt));
    }
    public function getNiceDate()
    {
        return  date('d.m.Y',strtotime($this->CreatedAt));
    }
    public function getComents(){

        return $this->hasMany(Coment::className(),['ArticleID'=> 'ID']);
    }
}

controllers/FBlogController.php
<?php
namespace app\controllers;

use app\modules\Category\models\Category;
use app\modules\Post\models\Post;
use yii\data\ActiveDataProvider;

class FBlogController extends \yii\web\Controller
{
    
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Category::find()->with('lang'),
            'pagination' => [
                'pageSize' => 1,
            ],
        ]);
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionCategory($id)
    {
        $category = Category::find()->with(['lang'])->where(['ID' => $id])->one();
        
        $dataProvider = new ActiveDataProvider([
            'query' => Post::find()->with(['lang', 'comments'])->where(['CategoryID' => $category->ID]),
            'pagination' => [
                'pageSize' => 1,
            ],
        ]);
        
        return $this->render('category', [
            'category' => $category, 
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPost($id)
    {
        $post = Post::find()->with('lang')->where(['ID' => $id])->one();
        
        return $this->render('post', [
            'post' => $post,
        ]);
    }

}

views/f-blog/_category_item.php
<?php

use yii\bootstrap\Html;

?>

<div class="col-md-4">
    <div>
        <?= Html::a($model->lang->Title, ['/f-blog/category', 'id' => $model->ID]) ?>
    </div>
    <hr />
</div>

views/f-blog/_item.php
<?php

use yii\bootstrap\Html;

?>

<div class="col-md-4">
    <div>
        <?= Html::a($model->lang->Title, ['/f-blog/post', 'id' => $model->ID]) ?>
    </div>
    <div>
        <?= $model->niceDate ?>
    </div>
    <div>
        <?= $model->shortContent ?>
    </div>
    <div>
        Comments: <?= count($model->comments) ?>
    </div>
    <hr />
</div>

views/f-blog/category.php
<?php

use yii\bootstrap\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
?>

<?= Html::tag('h1', $category->lang->Title) ?>

<?php \yii\widgets\Pjax::begin() ?>

    <div class="row">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_item',
            'layout' => "{items}<div class=\"clearfix\"></div>{pager}"
        ]); ?>
    </div>

<?php \yii\widgets\Pjax::end() ?>

views/f-blog/index.php
<?php

use yii\widgets\ListView;

/* @var $this yii\web\View */
?>

<?php \yii\widgets\Pjax::begin() ?>

    <div class="row">
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_category_item',
        ]); ?>
    </div>

<?php \yii\widgets\Pjax::end() ?>

views/f-blog/post.php
<?php

    use yii\bootstrap\Html;
    use app\modules\Comment\widgets\CommentWidget\CommentWidget;

?>


    <div>
        <?= $post->lang->Title ?>
    </div>
    <div>
        <?= $post->niceDate ?>
    </div>
    <div>
        <?= $post->lang->Content ?>
    </div>
    <div>
        <?= CommentWidget::widget([
            'postID' => $post->ID,
        ]) ?>
    </div>